---
# handlers file for roles/db
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html
- name: Restart Database
  # ansible.builtin.systemd:
  #   name: postgresql
  #   state: restarted
  ansible.builtin.debug:
    msg: "TODO: Restart Service (actual bug)"
