services:

  pilot:
    extends:
      file: docker-common.yml
      service: ansible
    hostname: pilot.localdomain
    ports:
      - ${SSH_PORT0:-22}:22

  host1:
    extends:
      file: docker-common.yml
      service: debiansshsystem12
    hostname: host1.localdomain
    ports:
      - ${SSH_PORT1:-23}:22

  host2:
    extends:
      file: docker-common.yml
      service: debiansshsystem12
    hostname: host2.localdomain
    ports:
      - ${SSH_PORT2:-24}:22